
PV_pn-ccsp-adv-security = "1.1.0"
PR_pn-ccsp-adv-security = "r0"

PV_pn-ccsp-cm-agent = "1.0.0"
PR_pn-ccsp-cm-agent = "r0"

PV_pn-ccsp-common-library = "1.1.0"
PR_pn-ccsp-common-library = "r0"

PV_pn-ccsp-common-library-native = "1.1.0"
PR_pn-ccsp-common-library-native = "r0"

PV_pn-ccsp-cr = "1.0.0"
PR_pn-ccsp-cr = "r0"

PV_pn-ccsp-dmcli = "1.0.0"
PR_pn-ccsp-dmcli = "r0"

PV_pn-ccsp-eth-agent = "1.2.0"
PR_pn-ccsp-eth-agent = "r0"

PV_pn-ccsp-gwprovapp = "1.1.0"
PR_pn-ccsp-gwprovapp = "r0"

PV_pn-ccsp-gwprovapp-ethwan = "1.0.0"
PR_pn-ccsp-gwprovapp-ethwan = "r0"

PV_pn-ccsp-home-security = "1.0.0"
PR_pn-ccsp-home-security = "r0"

PV_pn-ccsp-hotspot = "1.0.1"
PR_pn-ccsp-hotspot = "r0"

PV_pn-ccsp-hotspot-kmod = "1.0.0"
PR_pn-ccsp-hotspot-kmod = "r0"

PV_pn-ccsp-lm-lite = "1.1.0"
PR_pn-ccsp-lm-lite = "r0"

PV_pn-ccsp-misc = "1.1.0"
PR_pn-ccsp-misc = "r0"

PV_pn-ccsp-moca = "1.0.0"
PR_pn-ccsp-moca = "r0"

PV_pn-ccsp-mta-agent = "1.1.0"
PR_pn-ccsp-mta-agent = "r0"

PV_pn-ccsp-p-and-m = "1.1.0"
PR_pn-ccsp-p-and-m = "r0"

PV_pn-ccsp-psm = "1.0.1"
PR_pn-ccsp-psm = "r0"

PV_pn-ccsp-snmp-pa = "1.0.0"
PR_pn-ccsp-snmp-pa = "r0"

PV_pn-ccsp-tr069-pa = "1.0.0"
PR_pn-ccsp-tr069-pa = "r0"

PV_pn-ccsp-webui-bci-jst = "1.0.1"
PR_pn-ccsp-webui-bci-jst = "r0"

PV_pn-ccsp-webui-bci-php = "1.0.1"
PR_pn-ccsp-webui-bci-php = "r0"

PV_pn-ccsp-webui-jst = "1.0.2"
PR_pn-ccsp-webui-jst = "r0"

PV_pn-ccsp-webui-php = "1.0.2"
PR_pn-ccsp-webui-php = "r0"

PV_pn-ccsp-xconf = "1.0.0"
PR_pn-ccsp-xconf = "r0"

PV_pn-ccsp-xdns = "1.0.0"
PR_pn-ccsp-xdns = "r0"

PV_pn-core-net-lib = "1.0.0"
PR_pn-core-net-lib = "r0"

PV_pn-halinterface = "1.1.0"
PR_pn-halinterface = "r0"

PV_pn-hal-bridgeutil = "1.0.0"
PR_pn-hal-bridgeutil = "r0"

PV_pn-hal-cm-generic = "1.0.0"
PR_pn-hal-cm-generic = "r0"

PV_pn-hal-dhcpv4c-generic = "1.0.0"
PR_pn-hal-dhcpv4c-generic = "r0"

PV_pn-hal-epon-generic = "1.0.0"
PR_pn-hal-epon-generic = "r0"

PV_pn-hal-ethsw-generic = "1.0.0"
PR_pn-hal-ethsw-generic = "r0"

PV_pn-hal-firewall-generic = "1.0.0"
PR_pn-hal-firewall-generic = "r0"

PV_pn-hal-moca-generic = "1.0.0"
PR_pn-hal-moca-generic = "r0"

PV_pn-hal-mso-mgmt-generic = "1.0.0"
PR_pn-hal-mso-mgmt-generic = "r0"

PV_pn-hal-mta-generic = "1.0.0"
PR_pn-hal-mta-generic = "r0"

PV_pn-hal-platform-generic = "1.0.0"
PR_pn-hal-platform-generic = "r0"

PV_pn-hal-vlan-generic = "1.0.0"
PR_pn-hal-vlan-generic = "r0"

PV_pn-hal-wifi-generic = "1.0.0"
PR_pn-hal-wifi-generic = "r0"

PV_pn-harvester = "1.0.0"
PR_pn-harvester = "r0"

PV_pn-json-hal-lib = "2.0.0"
PR_pn-json-hal-lib = "r0"

PV_pn-jst = "1.0.0"
PR_pn-jst = "r0"

PV_pn-lanmanager = "1.0.0"
PR_pn-lanmanager = "r0"

PV_pn-notify-comp = "1.0.0"
PR_pn-notify-comp = "r0"

PV_pn-ovs-agent = "1.0.0"
PR_pn-ovs-agent = "r0"

PV_pn-powermgr = "1.0.0"
PR_pn-powermgr = "r0"

PV_pn-rdk-fwupgrade-manager = "1.0.0"
PR_pn-rdk-fwupgrade-manager = "r0"

PV_pn-rdk-cellularmanager = "1.1.1"
PR_pn-rdk-cellularmanager = "r0"

PV_pn-start-parodus = "1.0.0"
PR_pn-start-parodus = "r0"

PV_pn-test-and-diagnostic = "1.1.0"
PR_pn-test-and-diagnostic = "r0"

PV_pn-utopia = "1.1.2"
PR_pn-utopia = "r0"
