name: Auto PR Creation Caller

on:
  pull_request:
    types: [closed]
    branches:
      - develop
      - support/dunfell
      - 'support/*.*.*'
      - feature/Update-workflows

jobs:
  call_auto_pr_workflow:
    uses: rdkcentral/build_tools_workflows/.github/workflows/auto_pr_creation_rdkb_manifest.yml@feature/Update-workflows
    secrets:
      RDKCM_RDKE: ${{ secrets.RDKCM_RDKE }}
